#!/bin/sh

LOCDIR=${OPENSHIFT_REPO_DIR}markdown/notes/ # Run script from this directory
PUBDIR=${OPENSHIFT_REPO_DIR}html/notes/
FOOTER=${LOCDIR}_footer.html
NAVBAR=${LOCDIR}_navigation.html
PANOPTS="--smart --standalone --html5 -f markdown --template=${OPENSHIFT_REPO_DIR}etc/template.html --css=./bootstrap.css --css=./main.css --include-before-body=$NAVBAR"

# $PANOPTS above assume that the website template is in
# $HOME/.pandoc/templates/ and that the CSS file is in $PUBDIR.
# Next block assumes posts to be published are ...
# 1. In folders by category in $LOCDIR.
# 2. In markdown files with *.txt extension.
# 3. Contain a standard pandoc title block in first three lines.

> ${LOCDIR}.allposts
echo "Processing posts ..."
find `ls -l ${LOCDIR} | awk '/^d/ {print $NF}'` -type d -maxdepth 1 | \
while read -r folder
do
CATEGORY=$(basename "$folder")
for file in `ls "$folder"/*.mdown`
do
    if head -n 1 "$file" | grep -Eq "^%"; then
    POST=$(basename "$file" .mdown)
    TITLE=$(sed -n '1 s/% //p' "$file")
    POSTDATE=$(sed -n '3 s/% //p' "$file" | sed 's/[ ]$//')
    SORTDATE=$(date -d "$POSTDATE" +%y%m%d)
    RSSDATE=$(date -d "$POSTDATE" '+%a, %d %b %Y 00:00:00 %Z')
    pandoc $PANOPTS\
     --variable=category:"$CATEGORY"\
     --include-after-body="$FOOTER"\
     --output=${PUBDIR}/"$POST".html\
     "$file"
    CLIP=$(grep -m 1 -Eo '<p>.+</p>' $PUBDIR/"$POST".html) 
    echo ""$SORTDATE"%"$TITLE"%"$POST".html%"$POSTDATE"%"$RSSDATE"%"$CLIP""\
     >> ${LOCDIR}"$CATEGORY".mdown
    fi
done

cat ${LOCDIR}${CATEGORY}.mdown >> ${LOCDIR}.allposts

sort -nr ${LOCDIR}"$CATEGORY".mdown |\
 awk 'BEGIN{FS="%"};{print "* [" $2 "](" $3 ") | " $4 }'\
 > ${LOCDIR}.postlist
pandoc $PANOPTS \
 -A "$FOOTER" \
 --output=${PUBDIR}"$CATEGORY".html \
 ${LOCDIR}"$CATEGORY".pdc .postlist
rm ${LOCDIR}"$CATEGORY".mdown
done

echo "Processing index ..."
sort -nr ${LOCDIR}.allposts | sed -n '1,5 p'|\
 awk 'BEGIN{FS="%"};{print "* [" $2 "](" $3 ") | " $4 }'\
 > ${LOCDIR}recentposts.pdc 
pandoc $PANOPTS \
 -A "$FOOTER" \
 -o ${PUBDIR}index.html \
 ${LOCDIR}index.pdc ${LOCDIR}recentposts.pdc

echo "Processing RSS feed ..."
cp ${LOCDIR}_feed.xml ${PUBDIR}feed.xml
sort -nr ${LOCDIR}.allposts | sed -n '1,5 p'|\
 awk 'BEGIN{FS="%"}
 {print "\t<item>"}
 {print "\t\t<title>" $2 "</title>"}
 {print "\t\t<link>http://wcm1.web.rice.edu/" $3 "</link>"}
 {print "\t\t<guid>http://wcm1.web.rice.edu/" $3 "</guid>"}
 {print "\t\t<pubDate>" $5 "</pubDate>"}
 {print "\t\t<description>" $6 "[...]</description>\n\t</item>"}
 END{print "</channel>\n</rss>"}'\
 >> ${PUBDIR}feed.xml

exit 0
