#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

set -e

NGINX_DIR=${OPENSHIFT_RUNTIME_DIR}nginx/

umask 077

echo "Preprocessing nginx config."
cat ${OPENSHIFT_REPO_DIR}etc/nginx.conf.template | \
    ${OPENSHIFT_REPO_DIR}misc/expand_vars \
    > ${NGINX_DIR}conf/nginx.conf

echo "Starting nginx."
${NGINX_DIR}sbin/nginx
